defmodule Xeno.Repo.Migrations.AddNoteResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :filename, :text, null: false
      add :text, :text
      add :data, :map
      add :tags, {:array, :text}
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :directory_id,
          references(:directories,
            column: :id,
            name: "notes_directory_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :note_type_id, :uuid, null: false
    end

    create table(:note_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:notes) do
      modify :note_type_id,
             references(:note_types,
               column: :id,
               name: "notes_note_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:notes, [:directory_id, :filename],
             name: "notes_unique_filename_in_directory_index"
           )

    alter table(:note_types) do
      add :name, :text, null: false
      add :description, :text
      add :initial_text, :text
      add :initial_data, :map
      add :initial_tags, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:note_types, [:name], name: "note_types_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:note_types, [:name], name: "note_types_unique_name_index")

    alter table(:note_types) do
      remove :updated_at
      remove :inserted_at
      remove :initial_tags
      remove :initial_data
      remove :initial_text
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:notes, [:directory_id, :filename],
                     name: "notes_unique_filename_in_directory_index"
                   )

    drop constraint(:notes, "notes_note_type_id_fkey")

    alter table(:notes) do
      modify :note_type_id, :uuid
    end

    drop table(:note_types)

    drop constraint(:notes, "notes_directory_id_fkey")

    drop table(:notes)
  end
end
