defmodule Xeno.Repo.Migrations.RenamePathToPathLtree do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:directories, [:path])

    drop_if_exists unique_index(:directories, [:path], name: "directories_unique_path_index")

    rename table(:directories), :path, to: :path_ltree

    create index(:directories, [:path_ltree], using: "GIST")

    create unique_index(:directories, [:path_ltree], name: "directories_unique_path_index")
  end

  def down do
    drop_if_exists unique_index(:directories, [:path_ltree],
                     name: "directories_unique_path_index"
                   )

    drop_if_exists index(:directories, [:path_ltree])

    rename table(:directories), :path_ltree, to: :path

    create unique_index(:directories, [:path], name: "directories_unique_path_index")

    create index(:directories, [:path], using: "GIST")
  end
end
