defmodule Xeno.Repo.Migrations.AddUniqueFilenamePerParentToDirectories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:directories, [:filename, :parent_id],
             name: "directories_unique_filename_per_parent_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:directories, [:filename, :parent_id],
                     name: "directories_unique_filename_per_parent_index"
                   )
  end
end
