defmodule Xeno.Repo.Migrations.AddDirecoryTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:directories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :path, :ltree, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:directories, [:path], using: "GIST")

    create unique_index(:directories, [:path], name: "directories_unique_path_index")
  end

  def down do
    drop_if_exists unique_index(:directories, [:path], name: "directories_unique_path_index")

    drop_if_exists index(:directories, [:path])

    drop table(:directories)
  end
end
